# 工作流名称
name: 混淆并通过 SSH 部署到目标仓库

# 工作流触发器
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # ... [前面几个步骤保持不变] ...
      - name: 检出源仓库
        uses: actions/checkout@v4

      - name: 设置 Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: 安装 javascript-obfuscator
        run: npm install -g javascript-obfuscator

      # 步骤 4: 准备并混淆代码 (使用 WAF 友好型配置)
      - name: 混淆源文件
        run: |
          SOURCE_FILE="_worker.js"
          if [ -f "_worker.js.backup" ]; then
            SOURCE_FILE="_worker.js.backup"
          fi
          
          SEED=$(( $(date +%s) / 86400 ))
          echo "使用源文件: $SOURCE_FILE, 混淆种子: $SEED"

          # --- 使用对 Cloudflare WAF 更友好的配置 ---
          javascript-obfuscator $SOURCE_FILE --output _worker.js \
            --compact true \
            --seed $SEED \
            --control-flow-flattening true \
            --control-flow-flattening-threshold 0.5 \
            --dead-code-injection true \
            --dead-code-injection-threshold 0.1 \
            --disable-console-output true \
            --identifier-names-generator hexadecimal \
            --rename-globals true \
            --string-array true \
            --string-array-calls-transform true \
            --string-array-threshold 0.5 \
            --transform-object-keys true \
            # --- 以下是被修改或移除的关键参数 ---
            # 1. 移除了 unicode-escape-sequence (高风险)
            # 2. 将 string-array-encoding 设置为 'none' (默认值，高风险)
            #    (直接不写 --string-array-encoding 参数即可)
            # 3. 降低了 dead-code-injection-threshold 以减少注入

      # ... [后面几个步骤保持不变] ...
      - name: 检出目标仓库
        uses: actions/checkout@v4
        with:
          repository: 'joyfunfu/silent-wood-cc22'
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}
          path: 'deploy_repo'

      - name: 复制混淆文件并推送到目标仓库
        run: |
          cd deploy_repo
          cp ../_worker.js ./_worker.js
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "目标仓库代码无变化，跳过提交。"
          else
            git commit -m "chore: 更新 worker "
            git push
            echo "成功将更新推送到目标仓库。"
          fi
