# 工作流名称
name: 混淆并部署到目标仓库 (使用 PAT)

# 工作流触发器
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 步骤 1: 检出源仓库代码
      - name: 检出源仓库代码
        uses: actions/checkout@v4

      # 步骤 2: 设置 Node.js 环境
      - name: 使用 Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 步骤 3: 安装依赖
      - name: 安装依赖
        run: npm install -g javascript-obfuscator

      # 步骤 4: 准备源文件
      - name: 准备源文件
        run: |
          if [ ! -f _worker.js.backup ]; then
            cp _worker.js _worker_temp.js
          else
            cp _worker.js.backup _worker_temp.js
          fi
      
      # 步骤 5: 动态混淆代码
      - name: 动态混淆代码
        run: |
          SEED=$(( $(date +%s) / 86400 ))
          echo "今日混淆种子: $SEED"
          javascript-obfuscator _worker_temp.js --output _worker.js \
            --compact true --seed $SEED --control-flow-flattening true \
            --control-flow-flattening-threshold 0.75 --dead-code-injection true \
            --dead-code-injection-threshold 0.4 --disable-console-output true \
            --identifier-names-generator hexadecimal --rename-globals true \
            --self-defending true --string-array true --string-array-encoding 'rc4' \
            --string-array-threshold 0.75 --transform-object-keys true \
            --unicode-escape-sequence true

      # 步骤 6: 检出目标仓库 (使用新的 PAT 方式)
      - name: 检出目标仓库
        uses: actions/checkout@v4
        with:
          # ！！！ 确认目标仓库名正确 ！！！
          repository: 'joyfunfu/silent-wood-cc22'
          # 使用我们配置的 PAT 进行认证
          token: ${{ secrets.ACCESS_TOKEN }}
          # 将目标仓库克隆到 'deploy_repo' 文件夹
          path: 'deploy_repo'

      # 步骤 7: 复制混淆文件
      - name: 复制混淆文件
        run: |
          mkdir -p deploy_repo
          cp _worker.js ./deploy_repo/_worker.js

      # 步骤 8: 在目标仓库中提交并推送
      - name: 提交并推送到目标仓库
        run: |
          cd deploy_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _worker.js
          if git diff --staged --quiet; then
            echo "目标仓库代码无变化，跳过提交。"
          else
            git commit -m "chore: 每日更新 worker" -m "源自 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
            git push
            echo "成功将更新推送到目标仓库。"
          fi

