# 工作流名称
name: 混淆并部署到目标仓库 (使用 PAT)

# 工作流触发器
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # ... [前面几个步骤保持不变] ...
      - name: 检出源仓库代码
        uses: actions/checkout@v4

      - name: 使用 Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: 安装依赖
        run: npm install -g javascript-obfuscator

      - name: 准备源文件
        run: |
          if [ ! -f _worker.js.backup ]; then
            cp _worker.js _worker_temp.js
          else
            cp _worker.js.backup _worker_temp.js
          fi
      
      # 步骤 5: 动态混淆代码 (使用更安全的配置)
      - name: 动态混淆代码
        run: |
          SEED=$(( $(date +%s) / 86400 ))
          echo "今日混淆种子: $SEED"

          # --- 使用了对 Cloudflare Workers 更友好的配置 ---
          # 移除了 self-defending
          # 降低了 control-flow-flattening 的阈值
          javascript-obfuscator _worker_temp.js --output _worker.js \
            --compact true \
            --seed $SEED \
            --control-flow-flattening true \
            --control-flow-flattening-threshold 0.5 \
            --dead-code-injection true \
            --dead-code-injection-threshold 0.2 \
            --disable-console-output true \
            --identifier-names-generator hexadecimal \
            --rename-globals true \
            --string-array true \
            --string-array-encoding 'base64' \
            --string-array-threshold 0.5 \
            --transform-object-keys true \
            --unicode-escape-sequence false

      # ... [后面的步骤保持不变] ...
      - name: 检出目标仓库
        uses: actions/checkout@v4
        with:
          repository: 'joyfunfu/silent-wood-cc22'
          token: ${{ secrets.ACCESS_TOKEN }}
          path: 'deploy_repo'

      - name: 复制混淆文件
        run: |
          mkdir -p deploy_repo
          cp _worker.js ./deploy_repo/_worker.js

      - name: 提交并推送到目标仓库
        run: |
          cd deploy_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _worker.js
          if git diff --staged --quiet; then
            echo "目标仓库代码无变化，跳过提交。"
          else
            git commit -m "chore: 更新 worker"
            git push
            echo "成功将更新推送到目标仓库。"
          fi

